#' Simulated RD-DID panel (running variable fixed over time)
#'
#' A simulated panel in the setting of Leventer and Nevo: 1,000 units observed in
#' three years. A confounding policy `V` switches on above the cutoff (`R >= 0`)
#' in **every** year and raises the outcome by 0.5; the treatment of interest `W`
#' switches on above the cutoff only in year 3, the RD year, and raises the
#' outcome by 1. Years 1 and 2 are comparison years (nobody is treated), so the
#' jump in `Y` at the cutoff there is the confounding jump alone. The RD-DID
#' target is ATT(year 3) = 1; a plain RD in year 3 would recover 1.5.
#'
#' The running variable does not move between years, so every unit stays on the
#' same side of the cutoff ("panel, time-constant running variable").
#'
#' @format A data frame with 3,000 rows (one per unit-year) and 6 columns:
#' \describe{
#'   \item{id}{unit identifier, 1 to 1000.}
#'   \item{year}{1, 2 (comparison years) or 3 (the RD year).}
#'   \item{R}{running variable, uniform on \[-1, 1\]; the cutoff is 0.}
#'   \item{V}{confounding policy, 1 if `R >= 0` (every year).}
#'   \item{W}{treatment of interest, 1 if `R >= 0` and `year == 3`.}
#'   \item{Y}{outcome.}
#' }
#' @source Generated by `data-raw/make_sim.R` (seed 20261008). True effects:
#'   confounding jump 0.5 in every year, treatment effect 1.
#' @seealso [rddid_sim_pv] for the version with a moving running variable.
#' @examples
#' head(rddid_sim)
#' rddid(rddid_sim, y = "Y", x = "R", time = "year", id = "id", t_rd = 3)
"rddid_sim"

#' Simulated RD-DID panel (running variable moves over time)
#'
#' The same design as [rddid_sim] — confounding jump 0.5 in every year, treatment
#' effect 1 in year 3 — except that each unit's running variable drifts between
#' years (normal steps with standard deviation 0.15), so some units are above
#' the cutoff in one year and below it in another. These "switchers" are what
#' the validation tests ([rd_typecont()], [rd_compstable()], [rd_homog()],
#' [rd_trendcell()]) examine, and they make the sampling scheme "panel,
#' time-varying running variable".
#'
#' @format A data frame with 3,000 rows and the same 6 columns as [rddid_sim].
#' @source Generated by `data-raw/make_sim.R` (seed 20261009).
#' @seealso [rddid_sim].
#' @examples
#' # units that change side of the cutoff between years
#' sw <- tapply(rddid_sim_pv$V, rddid_sim_pv$id, function(v) length(unique(v)) > 1)
#' sum(sw)
#' rd_typecont(rddid_sim_pv, x = "R", time = "year", id = "id")
"rddid_sim_pv"
