#' Simulated RD-DID panel (running variable fixed over time)
#'
#' A simulated panel in the setting of Leventer and Nevo: 1,000 units observed in
#' three years. A confounding policy `V` switches on above the cutoff (`R >= 0`)
#' in **every** year and raises the outcome by 0.5; the treatment of interest `W`
#' switches on above the cutoff only in year 3, the RD period, and raises the
#' outcome by 1. Years 1 and 2 are the comparison periods (nobody is treated),
#' so the jump in `Y` at the cutoff there is the confounding jump alone. The
#' target of [rddid()] is the ATT in year 3, which is 1; a plain RD in year 3
#' would recover 1.5, the effect plus the confounding jump.
#'
#' The running variable does not move between years, so every unit stays on the
#' same side of the cutoff (sampling scheme "panel, running variable fixed over
#' time"). The tests of the assumptions are degenerate here: every unit keeps
#' its type, so there is nothing to test; [rddid_sim_pv] is the version for
#' the tests.
#'
#' @format A data frame with 3,000 rows (one per unit-year) and 6 columns:
#' \describe{
#'   \item{id}{unit identifier, 1 to 1000.}
#'   \item{year}{1, 2 (the comparison periods) or 3 (the RD period).}
#'   \item{R}{running variable, uniform on \[-1, 1\]; the cutoff is 0.}
#'   \item{V}{confounding policy, 1 if `R >= 0` (every year).}
#'   \item{W}{treatment of interest, 1 if `R >= 0` and `year == 3`.}
#'   \item{Y}{outcome.}
#' }
#' @source Generated by `data-raw/make_sim.R` (seed 20261008). True effects:
#'   confounding jump 0.5 in every year, treatment effect 1.
#' @seealso [rddid_sim_pv] for the version with a moving running variable.
#' @examples
#' head(rddid_sim)
#' rddid(rddid_sim, y = "Y", x = "R", time = "year", id = "id", t_rd = 3)
"rddid_sim"

#' Simulated RD-DID panel (running variable moves over time)
#'
#' The same design as [rddid_sim] (confounding jump 0.5 in every year, treatment
#' effect 1 in year 3), except that each unit's running variable drifts between
#' years (an independent normal deviation from the unit's base position, with
#' standard deviation 0 in year 1, 0.15 in year 2 and 0.30 in year 3), so some
#' units are above the cutoff in one year and below it in another. These
#' "switchers" are what the tests of the assumptions ([rd_typecont()],
#' [rd_compstable()], [rd_homog()], [rd_trendcell()]) examine, and they make the
#' sampling scheme "panel, running variable varies over time".
#'
#' By design, composition stability fails here: because the spread of the
#' deviations grows with the year, the mix of units near the cutoff (who was
#' above the cutoff in another year) is not the same in every year, and
#' [rd_compstable()] rejects. The confounding jump is nevertheless the same for
#' every unit, so homogeneous confounding holds ([rd_homog()] does not reject)
#' and [rddid()] still recovers the effect of 1. Type continuity and the
#' constant within-type jump also hold.
#'
#' @format A data frame with 3,000 rows and the same 6 columns as [rddid_sim].
#' @source Generated by `data-raw/make_sim.R` (seed 20261027, chosen with
#'   `data-raw/seed_scan.R` so that the assumptions that hold are comfortably
#'   not rejected and the one that fails clearly is).
#' @seealso [rddid_sim].
#' @examples
#' # units that change side of the cutoff between years
#' above <- rddid_sim_pv$R >= 0
#' sw <- tapply(above, rddid_sim_pv$id, function(a) length(unique(a)) > 1)
#' sum(sw)
#' rd_typecont(rddid_sim_pv, x = "R", time = "year", id = "id", t_rd = 3)
"rddid_sim_pv"
